repos:
 - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.1
    hooks:
     - id: sqlfluff-lint
       args: [--dialect, bigquery]
     - id: sqlfluff-fix
       args: [--dialect, bigquery]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
