default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: gdd-analytics-engineer
      dataset: "{{ 'dbt_' ~ env_var('USER') }}"
      threads: 4
      timeout_seconds: 300
      location: EU
      priority: interactive
    ci:
      dataset:  "{{ env_var('CI_DATASET') }}"
      keyfile: "{{ env_var('SA_KEYFILE') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      location: EU  
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: dbt_prod
      keyfile: "{{ env_var('SA_KEYFILE') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 8
      location: EU
      timeout_seconds: 300
      type: bigquery
