name: cd-dbt-build-upload-manifest

on:
  push:
    branches:
      - main # Run on merge to main

  workflow_dispatch: # Allow manual run

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  DBT_PROFILES_DIR: ${{ github.workspace }}
  SA_KEYFILE: ${{ github.workspace }}/.github/key.json

jobs:
  build-and-upload:
    name: Build DBT project (prod) and upload manifest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps

      - name: Set up service account key file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          printf '%s' "${GCP_SA_KEY}" > "$SA_KEYFILE"

      - name: Debug env (optional - remove later)
        run: |
          echo "GCP_PROJECT_ID=$GCP_PROJECT_ID"
          echo "SA_KEYFILE=$SA_KEYFILE"

      - name: Run dbt build with prod target
        run: dbt build --target prod

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload manifest.json to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: target/manifest.json
          destination: datenna-assessment/dbt_artifacts/manifest.json
          parent: false
