name: Manual dbt Build (Prod)

on:
  workflow_dispatch:

jobs:
  dbt-build-prod:
    name: Run dbt build with prod profile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account JSON file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/sa.json

      - name: Run dbt build with prod target
        run: dbt build --target prod
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }} # points to root where profiles.yml lives
          SA_KEYFILE: /tmp/sa.json
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
